[package]
name = "sealfs-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
lazy_static = "1.4.0"
anyhow = "1.0.66"
thiserror = "1.0.37"
log = "0.4.17"
clap = { version = "4.0.18", features = ["derive"] }
env_logger = "0.9.1"

client = {path = "client"}
server = {path = "server"}

[[bin]]
name = "client"
path = "src/bin/client.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[workspace]
members = [
    "server",
    "client",
    "common",
]
